# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: general.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rgeneral.proto\x12\x07General\x1a\x1bgoogle/protobuf/empty.proto\"g\n\trsMessage\x12,\n\x05param\x18\x01 \x03(\x0b\x32\x1d.General.rsMessage.ParamEntry\x1a,\n\nParamEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x0c:\x02\x38\x01\x32y\n\x0binteraction\x12\x32\n\x08\x64ispatch\x12\x12.General.rsMessage\x1a\x12.General.rsMessage\x12\x36\n\x04ping\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Emptyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'general_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_RSMESSAGE_PARAMENTRY']._options = None
  _globals['_RSMESSAGE_PARAMENTRY']._serialized_options = b'8\001'
  _globals['_RSMESSAGE']._serialized_start=55
  _globals['_RSMESSAGE']._serialized_end=158
  _globals['_RSMESSAGE_PARAMENTRY']._serialized_start=114
  _globals['_RSMESSAGE_PARAMENTRY']._serialized_end=158
  _globals['_INTERACTION']._serialized_start=160
  _globals['_INTERACTION']._serialized_end=281
# @@protoc_insertion_point(module_scope)
