# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rtsp.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nrtsp.proto\x12\x04rtsp\x1a\x1bgoogle/protobuf/empty.proto\"\x1a\n\x0bRTSPRequest\x12\x0b\n\x03url\x18\x01 \x01(\t\"\x1b\n\nVideoFrame\x12\r\n\x05\x66rame\x18\x01 \x01(\x0c\"d\n\trsMessage\x12)\n\x05param\x18\x01 \x03(\x0b\x32\x1a.rtsp.rsMessage.ParamEntry\x1a,\n\nParamEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x0c:\x02\x38\x01\x32K\n\x15RTSPStreamingServicer\x12\x32\n\x0bStreamVideo\x12\x11.rtsp.RTSPRequest\x1a\x10.rtsp.VideoFrame2s\n\x0binteraction\x12,\n\x08\x64ispatch\x12\x0f.rtsp.rsMessage\x1a\x0f.rtsp.rsMessage\x12\x36\n\x04ping\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Emptyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rtsp_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_RSMESSAGE_PARAMENTRY']._options = None
  _globals['_RSMESSAGE_PARAMENTRY']._serialized_options = b'8\001'
  _globals['_RTSPREQUEST']._serialized_start=49
  _globals['_RTSPREQUEST']._serialized_end=75
  _globals['_VIDEOFRAME']._serialized_start=77
  _globals['_VIDEOFRAME']._serialized_end=104
  _globals['_RSMESSAGE']._serialized_start=106
  _globals['_RSMESSAGE']._serialized_end=206
  _globals['_RSMESSAGE_PARAMENTRY']._serialized_start=162
  _globals['_RSMESSAGE_PARAMENTRY']._serialized_end=206
  _globals['_RTSPSTREAMINGSERVICER']._serialized_start=208
  _globals['_RTSPSTREAMINGSERVICER']._serialized_end=283
  _globals['_INTERACTION']._serialized_start=285
  _globals['_INTERACTION']._serialized_end=400
# @@protoc_insertion_point(module_scope)
