# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: test.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ntest.proto\x12\x03rpc\"\x17\n\x07\x43ontent\x12\x0c\n\x04text\x18\x01 \x01(\t\"\x16\n\x06Status\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x03\x32\x32\n\x03RPC\x12+\n\x0csendConfFile\x12\x0c.rpc.Content\x1a\x0b.rpc.Status\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'test_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_CONTENT']._serialized_start=19
  _globals['_CONTENT']._serialized_end=42
  _globals['_STATUS']._serialized_start=44
  _globals['_STATUS']._serialized_end=66
  _globals['_RPC']._serialized_start=68
  _globals['_RPC']._serialized_end=118
# @@protoc_insertion_point(module_scope)
